language: csharp
mono: none
dotnet: 2.2.300

branches:
  only:
    - master

install:
  - dotnet restore

script: 
  - dotnet build -c Release
  - dotnet pack PlusUltra.Nuget.HelloWorld.csproj --output pkg

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh
  on:
    branch: master