language: csharp
mono: none
dotnet: 2.2.300

branches:
  only:
    - master

install:
  - dotnet restore

script: 
  - dotnet build -c Release
  - dotnet pack PlusUltra.Nuget.HelloWorld.csproj --output /pkg/ --verbosity Detailed

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push /pkg/*.nupkg --source $NUGET_SOURCE --api-key 630d6ad2b55e9ae849039d564f5190930ad52326