language: csharp
mono: none
dotnet: 2.2.300

branches:
  only:
    - master

install:
  - dotnet restore

script: 
  - dotnet build -c Release
  - dotnet pack PlusUltra.Nuget.HelloWorld.csproj

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push *.nupkg --source $NUGET_SOURCE