language: csharp
mono: none
dotnet: 2.2.300

env:
  - PACKAGE_VERSION="1.0.2"

branches:
  only:
    - master

install:
  - dotnet restore

script: 
  - dotnet build -c Release
  - dotnet pack PlusUltra.Nuget.HelloWorld.csproj --output pkg /p:PackageVersion=$PACKAGE_VERSION

deploy:
  skip_cleanup: true
  provider: script
  script:  dotnet nuget push ./pkg/PlusUltra.Nuget.HelloWorld.$PACKAGE_VERSION.nupkg --source "GitHub"
  on:
    branch: master